#!/bin/bash
rm -rf build/apk/res
rm dist/*.apk
apktool b . ./dist/googlepinyin.dvorak.unaligned.apk
jarsigner -verbose -keystore /home/dheera/.android/debug.keystore -digestalg SHA1 -sigalg MD5withRSA dist/googlepinyin.dvorak.unaligned.apk debug
zipalign 4 dist/googlepinyin.dvorak.unaligned.apk dist/googlepinyin.dvorak.apk
rm dist/googlepinyin.dvorak.unaligned.apk
